config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :products
  resources :categories
  resources :users

  resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :carts, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end
  resources :orders, only: [:index, :show, :new, :create]

  root to: 'application#index'

  get '*path', to: 'application#not_found'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
    validates :title, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :image_url)
    end
    
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categoria or /categoria.json
  def index
    @category = Category.all
  end

  # GET /categoria/1 or /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @category = Category.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria or /categoria.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1 or /categoria/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1 or /categoria/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categoria_url, notice: "category was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :image_url)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="d-column">
    <strong>Nome:</strong>
    <%= category.title %>

    <br>

    <strong>Imagem:</strong>
    <%= category.image_url %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin-bottom: 15px">
    <%= form.label "Nome da Categoria", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div style="margin-bottom: 15px" class="field">
    <%= form.label "URL da Imagem", style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit "Criar Categoria", class: "btn btn-success text-white w-25" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="justify-content-center align-center">
  <p style="color: green"><%= notice %></p>
  <h1>Categorias</h1>

  <div class="row" id="categories" style="display: flex; text-align: center;">
    <% @categories.each do |category| %>
      <div class="col-md-4 mb-3">
        <div class="card custom-card" onclick="location.href='<%= category_path(category) %>';">
          <% if category.image_url.present? %>
            <%= image_tag category.image_url %>
          <% else %>
            <p>Imagem não disponível</p>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= category.title %></h5>
            <!-- Adicione mais informações da categoria conforme necessário -->
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "Nova categoria", new_category_path, class: "btn btn-success text-white w-25" %>
</div>

app/views/categories/new.html.erb
<div>
    <div style="margin-top: 15px; margin-bottom: 5px;">
        <%= link_to "Voltar", categories_path, class: "btn btn-primary custom-button w-25 align-left text-decoration-none text-white" %>
    </div>

    <h1>Nova categoria</h1>

    <br>

    <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div style="margin-top: 15px; margin-bottom: 5px;" class="justify-content-center">
  <div>
    <%= link_to "Voltar", categories_path, class: "btn btn-primary custom-button w-25 align-left text-decoration-none text-white" %>
  </button>
  </div>

<div class="card my-4 w-75">
  <div class="card-header bg-dark text-white py-2">
    Item
  </div>
  <div class="card-body w-100">
    <h3 class="card-title w-100 mb-4 mt-2"><%= @category.title %></h3>
    <div class="m-2 w-100">
      <%= link_to "Editar", edit_category_path(@category), class: " btn btn-dark mb-2 text-white mx-2 w-25" %>
      <%= button_to "Excluir", @category, method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-danger mb-2 mx-2 w-25 text-white" %>
    </div>
  </div>
</div>

  
</div>